version: "3"

services:
  oomnitza-connector:
    image: oomnitza/oomnitza-connector:latest
    env_file:
      - .env
    command: ["managed"]
    # volumes:
    #   - /path/config.ini:/app/config.ini

  oomnitza-connector-ldap:
    image: oomnitza/oomnitza-connector:latest
    env_file:
      - .env
    command: ["upload", "ldap"]
    # volumes:
    #   - /path/config.ini:/app/config.ini

  oomnitza-connector-csv-assets:
    image: oomnitza/oomnitza-connector:latest
    env_file:
      - .env
    command: ["upload", "csv_assets", "--testmode"]
    # volumes:
    #   - /path/config.ini:/app/config.ini
    #   - /another/path/on/local/machine:/home/appuser/exp/
