EnabledConnectors = (
    'oomnitza',

    'airwatch',
    'azuredevices',
    'azureusers',
    'bamboohr',
    'casper',
    'chef',
    'chromebooks',
    'google_mobile_devices',
    'csv_assets',
    'csv_users',
    'jasper',
    'ldap',
    'ldap_assets',
    'merakism',
    'mobileiron',
    'okta',
    'onelogin',
    'sccm',
    'zendesk',
    'csv_assets',
    'csv_users',
    'chromebooks',
)
